[package]
name = "template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
darling = "0.20.9"
features = "0.10.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.68"
tokio = "1.38.0"
